# Generated by Django 3.2.9 on 2021-12-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='Digital',
        ),
    ]
